import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import CookieContent from "@/component/CookieContent";
// import Navbar from "@/component/navbar/Navbar";
// import Footer from "@/component/footer/Footer";
// import { FaWhatsapp } from "react-icons/fa";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Feathers Transfers",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {/* <Navbar /> */}
        {children}
        <CookieContent/>
        {/* <Footer /> */}

        {/* WhatsApp Icon */}
        {/* <a
          href="https://wa.me/+33679524959" 
          target="_blank"
          rel="noopener noreferrer"
          className="fixed bottom-4 right-4 bg-green-500 text-white rounded-full p-4 shadow-lg hover:bg-green-600 transition-colors"
          aria-label="Chat with us on WhatsApp"
        >
          <FaWhatsapp size={30} /> 
        </a> */}
      </body>
    </html>
  );
}
